### ISSUE TITLE
Figure out 'wrong direction entered' for main.js

### ISSUE THREAD

**Issue by jawa9000** [CodeBytes-PDX/text_adventure_challenge#1]
While the move function works to move the player between rooms, it currently doesn't have a routine to handle invalid direction input. We'll need to either refactor updateLocation() function in main.js or come up with a different way to handle movement.

**Comment by jdsandifer** [comment]
This one is no longer applicable. Or we've taken the "come up with a different way to handle movement" approach to the solution - depending on your point of view.
